### ISSUE TITLE
Mention relevant comments in the Utility.py file

### ISSUE THREAD

**Issue by lakshyajit165** [IndianOpenSourceFoundation/dynamic-cli#44] opened 2021-03-21 14:45 UTC
## 📚 Documentation

The utility.py file contains functionalities which are used in fetching answers from APIs. It would be better to mention concise comments(before each function) mentioning the functionality of the methods and if the function is relatively long - a little bit of description about the flow as to what exactly that function does

**Comment by CyberneTech** [comment] 2021-03-22 02:36
Hey! I would like to work in this issue

**Comment by guptaaastha** [comment] 2021-03-27 03:31
Hello, I'd like to work on this issue, would be great if you could assign this to me.

**Comment by pranavbaburaj** [comment] 2021-03-27 05:13
Hello @GouravSardana, I'd also like to work on this. Please take me into consideration.

Hopefully @pranavbaburaj

**Comment by Nikita0509** [comment] 2021-03-28 18:56
Hello @GouravSardana @honeybhardwaj i would also like to work on this issue .

**Comment by honeybhardwaj** [comment] 2021-03-28 20:17
@Nikita0509 @pranavbaburaj  The issue is assigned to participants in First come First serve basis so you could grab other issues or create one for yourself.

**Comment by anshsrtv** [comment] 2021-04-13 18:47
Any updates? @guptaaastha

**Comment by guptaaastha** [comment] 2021-04-14 06:04
Had other commitments, I'll finish this by tomorrow :)

**Comment by guptaaastha** [comment] 2021-04-14 12:25
A PR has been raised 😄
@anshsrtv

**Closed** 2021-04-14 16:44 UTC
Labels: GSSoC21, Level0, assigned, documentation
